version: '3'

services:
  browseek:
    build: .
    volumes:
      - ./src:/app/src
      - ./examples:/app/examples

  example_service:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/example.local.crt:/etc/nginx/certs/example.local.crt
      - ./nginx/example.local.key:/etc/nginx/certs/example.local.key
      - ./html:/usr/share/nginx/html
      - ./images:/usr/share/nginx/html/images
    ports:
      - 443:443
