version: '3'

services:
  browseek:
    build: .
    volumes:
      - ./src:/app/src
      - ./examples:/app/examples
    env_file:
      - .env
    environment:
      - MAX_CONCURRENT_BROWSERS=${MAX_CONCURRENT_BROWSERS}
      - DEFAULT_TIMEOUT=${DEFAULT_TIMEOUT}
      - RETRY_ATTEMPTS=${RETRY_ATTEMPTS}
      - PROXY_ENABLED=${PROXY_ENABLED}
      - PROXY_ROTATE_ON_FAILURE=${PROXY_ROTATE_ON_FAILURE}
      - DNS_OVER_HTTPS=${DNS_OVER_HTTPS}
      - CAPTCHA_SERVICE=${CAPTCHA_SERVICE}
      - CAPTCHA_API_KEY=${CAPTCHA_API_KEY}
      - TEST_URL=${TEST_URL}
    ports:
      - "8080:8080"
    networks:
      - browseek_network

  example_service:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/example.local.crt:/etc/nginx/certs/example.local.crt
      - ./nginx/example.local.key:/etc/nginx/certs/example.local.key
      - ./html:/usr/share/nginx/html
      - ./images:/usr/share/nginx/html/images
    ports:
      - "443:443"
    networks:
      - browseek_network

networks:
  browseek_network:
    driver: bridge
